name: Action-03 Workflow
on: push
env:
  IMAGE_NAME: github-actions-nginx # workflow level variable

jobs:
  action-04_job_01:
    env:
      CONTAINER_REGISTRY: docker.io # job level variable
    runs-on: ubuntu-latest
    steps:
    - name: Docker Build
      env:
        DOCKER_USERNAME: siddharth1 # step level variable
      run: echo docker build -t ${{env.CONTAINER_REGISTRY}}/${{env.DOCKER_USERNAME}}/${{env.IMAGE_NAME}}:latest
    - name: Docker Login
      run: echo docker login --username=${{vars.REPO_DOCKER_USER}} --password=${{secrets.REPO_DOCKER_SECRET}}

  action-04_job_02:
    env:
      CONTAINER_REGISTRY: docker.io # job level variable
    runs-on: ubuntu-latest
    needs: [action-04_job_01]
    steps:
    - name: Docker Run
      env:
        DOCKER_USERNAME: siddharth1 # step level variable
      run: echo docker run -d -p 8080:90 ${{env.CONTAINER_REGISTRY}}/${{env.DOCKER_USERNAME}}/${{env.IMAGE_NAME}}:latest